

export function getSaves(page, pageSize) {
    return [
        {
            id: 2,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 3,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 13,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 1113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 11113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 111113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 1111113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 11111113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 111111113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 1111111113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },
        {
            id: 11111111113,
            name: "jack",
            content: "我想学习编程！",
            image: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
            likes: 100,
            avatar: "https://app2.sweden.com/wp-content/uploads/2019/10/Hawaii_TopSites_WaikikiBeach.jpg",
        },

    ]
}